# Generated by Django 4.1.1 on 2023-04-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('A', 'Male'), ('B', 'Female')], max_length=1, null=True),
        ),
    ]
