# Generated by Django 4.1.1 on 2022-11-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingaddress",
            name="phone",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
