# Generated by Django 4.1.1 on 2023-04-01 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_category_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flsh_sale',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
