# Generated by Django 4.1.1 on 2023-04-01 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_flsh_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='flsh_sale',
            new_name='flash_sale',
        ),
    ]
