# Generated by Django 4.1.1 on 2023-04-04 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_productimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
